spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.110.110:3306/cloud_user_center?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: root_mysql
      #连接池初始化,最小,最大
      initial-size: 5
      min-idle: 5
      max-active: 200
      #获取连接超时时间
      max-wait: 60000
      #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      #配置单个连接最小存活时间,单位毫秒
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #druid连接池开启慢sql监控
      filters: stat,wall,slf4j,config
      connect-properties:
        druid:
          stat:
            mergeSql: true
            slowSqlMillis: 5000
      # filter:
      #   stat:
      #     merge-sql: true
      #     slow-sql-millis: 5000
  #消息队列
  rabbitmq:
    host: 192.168.110.110
    port: 5672
    username: soulasuna
    password: root_rabbitmq    
#springboot整合mybatis配置
mybatis:
  #mapper文件加载路径
  mapper-locations: classpath*:**/Mapper/*.xml
  #javabean所在的基础包(可以是父级包名)
  type-aliases-package: com.dnt.cloud.common.pojo
  #mybatis的配置
  configuration:
    #数据库中null值也调用setter方法
    call-setters-on-nulls: true
    #驼峰命名与下划线相互转换
    map-underscore-to-camel-case: true

#自定义参数配置
custom:
  config:
    druid:
      monitor:
        servletIpWhiteAllow: 127.0.0.1
        servletIpBlackDeny: 192.168.110.111
        servletLoginUserName: admin
        servletLoginPassWord: admin_druid
        servletResetEnable: false
        filterPathExclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"

        # servlet-ip-white-allow: 127.0.0.1
        # servlet-ip-black-deny: 192.168.110.111
        # servlet-login-user-name: admin
        # servlet-login-pass-word: admin_druid
        # servlet-reset-enable: false
        # filter-path-exclusions: *.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*





