spring:
  profiles:
    active: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.110.110:3306/cloud_message?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: root_mysql
      #连接池初始化,最小,最大
      initial-size: 5
      min-idle: 5
      max-active: 200
      #获取连接超时时间
      max-wait: 60000
      #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      #配置单个连接最小存活时间,单位毫秒
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #druid连接池开启慢sql监控
      filters: stat,wall,slf4j,config
      connect-properties:
        druid:
          stat:
            mergeSql: true
            slowSqlMillis: 5000

  #消息队列
  rabbitmq:
    host: 192.168.110.110
    port: 5672
    username: soulasuna
    password: root_rabbitmq

  #redis配置信息
  redis:
    host: 192.168.110.110
    port: 6379
    # Redis数据库索引（默认为0）
    database: 0
    password: root_redis
    # 连接超时时间（毫秒)
    timeout: 1000
    lettuce:
      # 关闭超时链接时间
      shutdown-timeout: 100
      pool:
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 10000
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 200
        # 连接池中的最小空闲连接
        min-idle: 0

#springboot整合mybatis配置
mybatis:
  #mapper文件加载路径
  mapper-locations: classpath*:**/Mapper/*.xml
  #javabean所在的基础包(可以是父级包名)
  type-aliases-package: com.dnt.cloud.message.pojo.po
  #mybatis的配置
  configuration:
    #数据库中null值也调用setter方法
    call-setters-on-nulls: true
    #驼峰命名与下划线相互转换
    map-underscore-to-camel-case: true

#自定义参数配置
custom:
  config:
    #druid数据源配置
    druid:
      monitor:
        servletIpWhiteAllow: 127.0.0.1
        servletIpBlackDeny: 192.168.110.111
        servletLoginUserName: admin
        servletLoginPassWord: admin_druid
        servletResetEnable: false
        filterPathExclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
    #api文档swagger-ui配置
    api:
      swagger:
        enable: true
        apiInfoTitle: "SpringBoot基于Swagger2构建RESTful-API"
        apiInfoDescription: "商户中心模块"
        apiInfoVersion: "V1.0.0"
        apiInfoContactName: "soulasuna"
        apiInfoContactUrl: "https://github.com/soulasuna/cloud-geenwich-general/tree/master/suncloud-message"
        apiInfoContactEmail: "jacky7boy@163.com"
        scanBasePackage: "com.dnt.cloud.merchant.controller"
    #线程池配置
    pool:
      #消息生产者线程池参数配置
      producerTaskExecutor:
        corePoolSize: 16
        maxPoolSize: 64
        queueCapacity: 100
        threadNamePrefix: rabbitProducerExecutor
        keepAliveSeconds: 60

  factory:
    models:
      #redis_lock
      - id: redisLock
        path: com.dnt.cloud.common.framework.lock.redis.RedisLock
